Inventory_system/Inventory/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Inventory'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('register/',views.register,name='register'),

    path('',views.product_list,name='product_list'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('edit/<int:product_id>/', views.manage_product, name='edit_product'),
    path('add/', views.manage_product, name='create_product'),

    path('category/',views.category_list,name='category_list'),
    path('category/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('category/edit/<int:category_id>/', views.manage_category, name='edit_category'),
    path('category/add/', views.manage_category, name='create_category'),

    path('sales/', views.sales_list, name='sales_list'),
    path('sales/<int:pk>/', views.sales_detail, name='sales_detail'),
    path('sales/create/', views.create_sales, name='create_sales'),

    path('report/', views.inventory_report, name='inventory_report'),
]

Inventory_system/Inventory_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Inventory.urls',namespace='Inventory')),
]

Inventory_system/Inventory/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Sales(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(max_length=100)
    sale_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Sale {self.id} by {self.user.username}"

class SalesDetail(models.Model):
    sale = models.ForeignKey(Sales, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_sold = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Sale {self.sale.id} - {self.product.name}"

Inventory_system/Inventory/forms.py
from django import forms
from .models import Product,Category,Sales,SalesDetail
from django.contrib.auth.models import User

class ProductForm(forms.ModelForm):
    class  Meta:
        model = Product
        fields = ['name', 'price', 'quantity', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter product name'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter product price'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter quantity', 'min': 1}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name','description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter category name'}),
            'description' :forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter category name'})
        }

class SalesForm(forms.ModelForm):
    class Meta:
        model = Sales
        fields = ['payment_method']

class SalesDetailForm(forms.ModelForm):
    class Meta:
        model = SalesDetail
        fields = ['product', 'quantity_sold']
    



class RegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}),
        label="Password"
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm your password'}),
        label="Confirm Password"
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}),
        label="Email"
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}),
        label="Username"
    )

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data

Inventory_system/Inventory/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.db import transaction
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm
from .models import Product,Category,Sales,SalesDetail
from django.db.models import Sum
from django.forms import inlineformset_factory
from .forms import ProductForm,CategoryForm,SalesForm,SalesDetailForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            login(request, user)
            messages.success(request, "Registration successful!")
            return redirect('Inventory:product_list')
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        form = RegistrationForm()

    return render(request, 'registration/register.html', {'form': form})

@login_required
def product_list(request):
    products = Product.objects.all().order_by("name")
    context = {'products':products}
    return render(request,'product/product_list.html',context)

@login_required
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        product.delete()
        return redirect('Inventory:product_list') 
    return render(request, 'product/delete_product.html', {'product': product})

@login_required
def manage_product(request, product_id=None):
    if product_id:
        product = get_object_or_404(Product, id=product_id)
    else:
        product = None

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('Inventory:product_list')  
    else:
        form = ProductForm(instance=product)

    return render(request, 'product/manage_product.html', {'form': form, 'product': product})


# category
@login_required
def category_list(request):
    categories = Category.objects.all().order_by("name")
    context = {'categories':categories}
    return render(request,'category/category_list.html',context)

@login_required
def delete_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.method == 'POST':
        category.delete()
        return redirect('Inventory:category_list')
    return render(request, 'category/delete_category.html', {'category': category})

@login_required
def manage_category(request, category_id=None):
    if category_id:
        category = get_object_or_404(Category, id=category_id)
    else:
        category = None

    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('Inventory:category_list')  
    else:
        form = CategoryForm(instance=category)

    return render(request, 'category/manage_category.html', {'form': form, 'category': category})

# Sales Views
@login_required
def sales_list(request):
    sales = Sales.objects.all().order_by('-sale_date')
    return render(request, 'sales/sales_list.html', {'sales': sales})

@login_required
def sales_detail(request, pk):
    sale = get_object_or_404(Sales, pk=pk)
    sales_details = SalesDetail.objects.filter(sale=sale)
    return render(request, 'sales\sales.detail.html', {'sale': sale, 'sales_details': sales_details})


@login_required
def create_sales(request):
    SalesDetailFormSet = inlineformset_factory(
        Sales,
        SalesDetail,
        form=SalesDetailForm,
        extra=3,
        can_delete=False,
    )

    if request.method == 'POST':
        sales_form = SalesForm(request.POST)
        formset = SalesDetailFormSet(request.POST)

        if sales_form.is_valid() and formset.is_valid():
            with transaction.atomic():
                sale = sales_form.save(commit=False)
                sale.user = request.user
                sale.total_amount = 0
                sale.save()
                
                has_errors = False 
                for detail in formset.save(commit=False):
                    
                    
                    if detail.product  and detail.quantity_sold > 0:
                        if detail.quantity_sold > detail.product.quantity:
                            detail.add_error('quantity_sold', f"Not enough stock for {detail.product.name}.")
                            has_errors = True
                            continue

                        detail.sale = sale
                        detail.price = detail.product.price
                        detail.total_price = detail.quantity_sold * detail.price
                        detail.product.quantity -= detail.quantity_sold
                        detail.product.save()
                        sale.total_amount += detail.total_price
                        detail.save()
                
                if has_errors:
                    return render(request, 'sales/create_sales.html', {
                        'sales_form': sales_form,
                        'formset': formset,
                    })
                sale.save()
                return redirect('Inventory:sales_list')

    else:
        sales_form = SalesForm()
        formset = SalesDetailFormSet()

    return render(request, 'sales/create_sales.html', {
        'sales_form': sales_form,
        'formset': formset,
})

@login_required
def inventory_report(request):
    products = Product.objects.all()

    sales_summary = Sales.objects.aggregate(
        total_sales=Sum('total_amount')
    )

    sales_details = SalesDetail.objects.values(
        'product__name'
    ).annotate(
        total_sold=Sum('quantity_sold'),
        total_earnings=Sum('total_price')
    ).order_by('-total_earnings')

    categories = Category.objects.all()

    context = {
        'products': products,
        'sales_summary': sales_summary,
        'sales_details': sales_details,
        'categories': categories,
    }
    return render(request, 'report.html', context)

Inventory_system/Inventory/templates/category/category_list.html
{% extends "index.html" %}
{% block body%}
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center">Category List</h1>
        <!-- New category Button -->
        <div class="text-end mb-3">
            <a href="{% url "Inventory:create_category"%}" class="btn btn-success">Add New Category</a>
        </div>
        <table class="table table-striped table-hover mt-4">
            <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ category.name }}</td>
                    <td>{{ category.description }}</td>
                    <td>
                        <a href="{% url 'Inventory:edit_category' category.id %}" class="text-primary me-4">
                            <i class="bi bi-pen fs-6"></i>
                        </a>
                        <a href="{% url 'Inventory:delete_category' category.id  %}" class="text-danger">
                            <i class="bi bi-x-circle fs-6"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="text-center">No Categories available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
{% endblock %}

Inventory_system/Inventory/templates/category/delete_category.html
{% extends 'index.html' %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center">Delete Category</h1>

    <!-- Confirmation Card -->
    <div class="card">
        <div class="card-header">
            <h3>Are you sure you want to delete the Category: {{ category.name }}?</h3>
        </div>
        <div class="card-body">
            <p><strong>Description:</strong> {{ category.description }}</p>
        </div>

        <!-- Confirmation Form -->
        <div class="card-footer">
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                <a href="{% url 'Inventory:category_list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Inventory_system/Inventory/templates/category/manage_category.html
{% extends 'index.html'%}
{% block body %}
<div class="container mt-5">
    <h1 class="text-center">
        {% if category %}
            Edit Category
        {% else %}
            New Category
        {% endif %}
    </h1>
    
    <div class="card">
        <div class="card-header">
            <h3 class="text-center">
                {% if category %}
                    Edit Category
                {% else %}
                    New Category
                {% endif %}
            </h3>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}  
                <button type="submit" class="btn btn-success">
                {% if category %}
                    EDIT 
                {% else %}
                    ADD
                {% endif %}
                </button>
                <a href="{% url 'Inventory:category_list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}